version: "0.2"
language: en
ignorePaths:
  - node_modules/**
  - tsconfig.*
  - yarn.lock
  - .eslintrc.cjs
dictionaryDefinitions: []
dictionaries: []
words:
  - Avenir
  - iconsets
  - Pinia
  - Vuetify
ignoreWords: []
import: []
