name: App to DockerHub

on:
  push:
    branches:
      - 'feature-gha-dockerhub-watchtower'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          secret-files: |
            "ENV_PARAMS=${{ secrets.ENV_PARAMS }}"
            "ENV_PARAMS_FRONT=${{ secrets.ENV_PARAMS_FRONT }}"
          push: true
          tags: user/app:latest