name: CD

on:
  push:
    branches:
      - 'feature-gha-dockerhub-watchtower'
defaults:
  run:
    working-directory: ./
jobs:
  docker:
    runs-on: ubuntu-latest
    #needs: ci
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
        with:
           ref: feature-gha-dockerhub-watchtower
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: LS
        run: ls -la
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          # context: .
          # file: ./Dockerfile
          secret-files: |
            "ENV_PARAMS=${{ secrets.ENV_PARAMS }}"
            "ENV_PARAMS_FRONT=${{ secrets.ENV_PARAMS_FRONT }}"
          push: true
          tags: user/app:latest