name: CD

on:
  push:
    branches:
      - 'production'

permissions:
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest
    #needs: ci
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      -
        name: LS
        run: ls -la
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Set env
        run: echo "DATE=$(date +%s)" >> $GITHUB_ENV
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          secrets: |
            "ENV_PARAMS=${{ secrets.ENV_PARAMS }}"
            "ENV_PARAMS_FRONT=${{ secrets.ENV_PARAMS_FRONT }}"
          push: true
          tags: dasna/not_twitter:latest