name: Deploy ExpressJS

on:
  push:
    branches: [ release0.1, production, feature-readme-dotenv-gha-cookies ]
  pull_request:
    branches: [ release0.1, production, feature-readme-dotenv-gha-cookies ]
jobs:
  deploy_expressJS:
    name: Deploying ExpressJS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install packages
      run: npm ci
    - name: Load Secrets
      run: 'echo "$ENV_PARAMS" > backend/.env'
      shell: bash
      env:
        ENV_PARAMS: ${{ secrets.ENV.PARAMS }}
    - name: Check Secrets
      run: cat backend/.env
    - name: Building Express
      run: npm run build:express
    - name: Starting Express
      run: node backend/dist/src/api.js &
    - name: Testing Express
      run: npm run test:unit:backend:single
  # test_expressJS:
  #   needs: [deploy_expressJS]
  #   name: Testing ExpressJS"
  #   runs-on: ubuntu-latest

  #   strategy:
  #   matrix:
  #     node-version: [16.x]


  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Use Node.js ${{ matrix.node-version }}
  #     uses: actions/setup-node@v2
  #     with:
  #       node-version: ${{ matrix.node-version }}
  #       cache: 'npm'
  #   - name: Install packages
  #     run: npm ci
  #   - name: Building Express
  #   - run: npm run build:express
